/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qmfmnglunbqsxsdfqmyd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZm1uZ2x1bmJxc3hzZGZxbXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTI1MTAsImV4cCI6MjA3NDI4ODUxMH0.72L-x1InGhJC3oAnky_NmtMqfds-aiIUL3Agd8xf-mY"